name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the image'
        required: false
        default: false
        type: boolean
      tags:
        description: 'Docker tags to apply'
        required: false
        default: ''
        type: string
      labels:
        description: 'Docker labels to apply'
        required: false
        default: ''
        type: string
      platforms:
        description: 'Target platforms'
        required: false
        default: 'linux/amd64,linux/arm64'
        type: string
      registry:
        description: 'Container registry'
        required: false
        default: 'ghcr.io'
        type: string
    secrets:
      registry-token:
        description: 'Registry authentication token'
        required: false

env:
  REGISTRY: ${{ inputs.registry }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      if: ${{ inputs.push }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.registry-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags || format('{0}/{1}:test', env.REGISTRY, env.IMAGE_NAME) }}
        labels: ${{ inputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
